/**
 * AGENTS.md generator.
 *
 * The corpus finding behind this file: the repositories that stay coherent
 * under many contributors — human or agent — state their layout contract where
 * the worker will read it, and 10 of the 18 reference repositories ship an
 * agent-instructions file. For a vibe-coded project this is the cheapest
 * possible drift brake, because the contract is derived from the same
 * `.structure/guard.json` that `audit` enforces, so the prose cannot silently
 * disagree with the machine.
 *
 * Generated prose is regenerated; the CURATED block is carried over verbatim,
 * exactly like the architecture digest.
 */

const CURATED_BEGIN = '<!-- BEGIN CURATED -->';
const CURATED_END = '<!-- END CURATED -->';

export function extractCurated(existing) {
  if (typeof existing !== 'string') return undefined;
  const start = existing.indexOf(CURATED_BEGIN);
  const end = existing.indexOf(CURATED_END);
  if (start === -1 || end === -1 || end < start) return undefined;
  const inner = existing.slice(start + CURATED_BEGIN.length, end);
  const body = inner.split('\n').filter((line) => !/^\s*<!--\s*(BEGIN|END) CURATED\s*-->\s*$/.test(line)).join('\n');
  return body.trim() === '' ? undefined : body.replace(/^\n+/, '').replace(/\s+$/, '');
}

const DEFAULT_CURATED = `## Project intent (curated — never regenerated)

_What this project is for, the rules a change must respect, and anything the tables above
cannot know. This block survives every regeneration of AGENTS.md._

- Purpose:
- Non-negotiable rules:
- Known exceptions:
`;

/** Render AGENTS.md from the live snapshot, the declared contract and the current audit. */
export function renderAgents(snapshot, { config, findings = [], existing, guardCommand } = {}) {
  const { metrics, project, conventions, topLevel } = snapshot;
  const out = [];
  const push = (line = '') => out.push(line);

  push('<!-- structure-guard: generated by `guard.mjs agents` — tables are regenerated, the CURATED block is yours. -->');
  push(`# AGENTS.md — ${project.name ?? 'this project'}`);
  push('');
  push('> Generated from `.structure/guard.json` and the current tree. Regenerate with');
  push(`> \`${guardCommand ?? 'node ~/.dsh/skills/structure-guard/scripts/guard.mjs'} agents .\``);
  push('> Editing the tables by hand is pointless: they are derived. Change `guard.json` instead.');
  push('');

  push('## What this is');
  push('');
  push(`- Layout archetype: \`${project.archetype}\` · primary language: \`${conventions.primaryLanguage}\` · module system: \`${conventions.moduleSystem}\``);
  push(`- Size: ${metrics.files} tracked files, ${metrics.sourceFiles} source files, ~${metrics.sourceLoc} source lines, max depth ${metrics.maxDepth}`);
  push(`- Tests: ${metrics.testFiles} file(s), placement \`${conventions.testStyle}\`, ratio ${metrics.testToSourceRatio ?? '—'}`);
  push(`- Package manager: \`${conventions.packageManager ?? 'unknown'}\`${project.version ? ` · version ${project.version}` : ''}`);
  const entryPoints = (topLevel ?? []).filter((t) => t.entry).map((t) => `\`${t.entry}\``);
  if (entryPoints.length > 0) push(`- Entry points: ${entryPoints.slice(0, 6).join(', ')}`);
  push('');

  const modules = config?.modules ?? [];
  const boundaries = new Map((config?.boundaries ?? []).map((b) => [b.from, b.mayImport ?? []]));
  if (modules.length > 0) {
    push('## Layout contract');
    push('');
    push('These modules are declared, and `guard.mjs audit` fails when an import breaks them.');
    push('');
    push('| Module | Layer | Paths | May import | Purpose |');
    push('| --- | --- | --- | --- | --- |');
    for (const mod of modules) {
      const layer = mod.layer === null || mod.layer === undefined ? '—' : mod.layer;
      const may = boundaries.has(mod.name)
        ? (boundaries.get(mod.name).length > 0 ? boundaries.get(mod.name).map((x) => `\`${x}\``).join(', ') : '_nothing_')
        : '_undeclared_';
      const paths = (mod.paths ?? []).map((p) => `\`${p}\``).join(', ');
      push(`| \`${mod.name}\` | ${layer} | ${paths} | ${may} | ${config.describe?.[mod.name] ?? ''} |`);
    }
    push('');
    push('Lower layers are inner: an import may only point from a higher layer to a lower one, and only where the row above allows it.');
    push('');
  }

  const errors = findings.filter((f) => f.severity === 'error');
  const warns = findings.filter((f) => f.severity === 'warn');
  push('## Current structural state');
  push('');
  if (errors.length === 0 && warns.length === 0) {
    push('- `audit`: clean — no errors or warnings.');
  } else {
    if (errors.length > 0) {
      push(`- **${errors.length} error(s) that must be fixed or explicitly waived**: ${errors.map((f) => `\`${f.ruleId}\``).join(', ')}`);
    }
    if (warns.length > 0) {
      push(`- ${warns.length} warning(s) to justify or fix: ${warns.map((f) => `\`${f.ruleId}\``).join(', ')}`);
    }
  }
  push('');

  push('## Working here');
  push('');
  push('```sh');
  push(`${guardCommand ?? 'node ~/.dsh/skills/structure-guard/scripts/guard.mjs'} audit .    # structure + drift, before you commit`);
  push(`${guardCommand ?? 'node ~/.dsh/skills/structure-guard/scripts/guard.mjs'} verify .   # audit + typecheck + tests + build`);
  push('```');
  push('');
  push('- **Do not re-baseline to silence a finding.** `baseline` is for an intended change: record why in `ARCHITECTURE.md`, update `guard.json` if a boundary moved, then re-baseline.');
  push('- A new top-level directory or module is a structural decision, not a detail: declare it in `guard.json` in the same change.');
  push('- New code goes where `describe` in `guard.json` says it goes. If no module fits, the contract is missing a module — add it deliberately.');
  push('- Keep `ARCHITECTURE.md` current (`digest`); a stale digest fails CI.');
  push('');

  push(CURATED_BEGIN);
  const curated = extractCurated(existing) ?? DEFAULT_CURATED.trimEnd();
  push(curated.startsWith('#') || curated.startsWith('##') ? `## ${curated.replace(/^#+\s*/, '')}` : curated);
  push(CURATED_END);
  push('');

  return out.join('\n');
}
